# Generated by Django 5.2.7 on 2025-11-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view a book'), ('can_create_book', 'Can create a book'), ('can_edit_book', 'Can edit a book'), ('can_delete_book', 'Can delete a books')]},
        ),
    ]
