"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def get_secret_key():
    key = os.environ.get('SECRET_KEY')
    return key if key else 'django-insecure-ew!v@ohsqt44&(=%qi47z)z6i48(7*l^+76-1$jb*6x_$mda1&'

SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
def get_debug_setting():
    debug_value = os.environ.get('DEBUG', 'False')
    return debug_value.lower() == 'true' if debug_value else False

DEBUG = get_debug_setting()

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# ============================================================================
# HTTPS AND SECURITY CONFIGURATION
# ============================================================================

# Step 1: HTTPS Enforcement Settings
# Redirect all non-HTTPS requests to HTTPS
SECURE_SSL_REDIRECT = not DEBUG  # Enable in production (when DEBUG=False)

# HTTP Strict Transport Security (HSTS) - Force browsers to use HTTPS
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG  # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = not DEBUG  # Allow preloading in browser HSTS lists

# Step 2: Secure Cookie Configuration
# Ensure session cookies are only transmitted over HTTPS
SESSION_COOKIE_SECURE = not DEBUG  # Enable in production
# Ensure CSRF cookies are only transmitted over HTTPS
CSRF_COOKIE_SECURE = not DEBUG  # Enable in production
# Prevent JavaScript access to cookies (XSS protection)
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

# Step 3: Security Headers Implementation
# Prevent clickjacking attacks by denying framing
X_FRAME_OPTIONS = 'DENY'
# Prevent MIME type sniffing attacks
SECURE_CONTENT_TYPE_NOSNIFF = True
# Enable browser's built-in XSS filtering
SECURE_BROWSER_XSS_FILTER = True

# Proxy SSL Header - For deployment behind reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional Security Headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_PERMISSIONS_POLICY = {
    'geolocation': [],
    'microphone': [],
    'camera': [],
    'payment': [],
    'usb': [],
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Content Security Policy - Prevent XSS attacks by controlling resource loading
try:
    import csp
    MIDDLEWARE.insert(1, 'csp.middleware.CSPMiddleware')
except ImportError:
    pass

# CSP Directives - Define allowed sources for different content types
CSP_DEFAULT_SRC = ("'self'",)  # Default policy: only same origin
CSP_SCRIPT_SRC = ("'self'",)  # Scripts: only from same origin
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",)  # Styles: same origin + inline
CSP_FONT_SRC = ("'self'",)  # Fonts: only from same origin
CSP_IMG_SRC = ("'self'", "data:",)  # Images: same origin + data URLs

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/books/'
LOGOUT_REDIRECT_URL = '/login/'
